### ISSUE TITLE
Unable to copy file "obj\Debug\ExSharpBase.exe" to "bin\Debug\ExSharpBase.exe".Could not find the file “obj\Debug\ExSharpBase.exe”

### ISSUE THREAD

**Issue by clearloveuzi777** [ZeroLP/ExSharp-Base#15]
Hi, I am totally new to code🤣. I just downloaded Visual Studio 2019 and tried to build exe, but it showed this. I guess it might be because the zip on github doesn't have original exe file, Could anyone tell me how to build my own exe file on my computer?

**Comment by azorkai** [comment]
try to rebuild

**Comment by clearloveuzi777** [comment]
Found the problem! Avast Antivirus killed my file. Added exemption and it works well.
