### ISSUE TITLE
Auto update spelldb and unitradious

### ISSUE THREAD

**Issue by nerdunit** [ZeroLP/ExSharp-Base#16]
Hi, I made a project that uses riot's data dragon to make a build for bots (https://github.com/nerdunit/LeagueRecommendBuild)
It shouldn't be hard to modify it to get the same data as your spelldb.json and this would make it automatic.
I would do it myself but I'm not good enough at coding to implement it in your base

**Comment by ZeroLP** [comment]
The SpellDB.json was retrieved by my other project: https://github.com/ZeroLP/SpellDB
