### ISSUE TITLE
ERROR REPORTING

### ISSUE THREAD

**Issue by FlavinDoPneu** [ZeroLP/ExSharp-Base#6]
**EXCEPTION THROWN:** SpellDBParseException
**EXCEPTION MESSAGE:** Object reference not set to an instance of an object
**ERROR OCCURRING LINE/FILE:** 19 / "...\Modules\SpellDBService.cs"
**YOUR ACTION BEFORE OCCURRENCE OF THE ERROR:** I just open and the error appears
**ANY RESOLUTION YOU HAVE TAKEN BEFORE RAISING THIS ISSUE:** 1366x768
**LEAGUE OF LEGENDS VERSION:** 10.16.3309186
**LEAGUE OF LEGENDS SERVER REGION:** Brazil

**PS:**  For while it just appears playing with:
 - Lee Sin;
- KhaZix

**Comment by chublee** [comment]
did you run as admin?

**Comment by FlavinDoPneu** [comment]
> did you run as admin?

Yes, every times

**Comment by chublee** [comment]
it could be a problem caused by the mismatch of the locale string. try debugging with the breakpoint at spelldbservice.cs and changing the client locale if it's a problem caused by the champion's name.

try run lol with command line arguments.
```
"C:\Riot Games\League of Legends\LeagueClient.exe" --locale=en_US
```

**Comment by FlavinDoPneu** [comment]
> it could be a problem caused by the mismatch of the locale string.[...] 

That's right !! In the file(SpellDB.json), champions with compound names or single quotes (') had to make the necessary changes, such as:

AurelionSol -> Aurelion Sol
Chogath -> Cho'Gath
DrMundo -> Dr. Mundo
JarvanIV -> Jarvan IV
Khazix -> Kha'Zix
KogMaw -> Kog'Maw
LeeSin -> Lee Sin
MasterYi -> Master Yi
MissFortune -> Miss Fortune
MonkeyKing -> Wukong
RekSai -> Rek'Sai
TahmKench -> Tahm Kench
TwistedFate -> Twisted Fate
XinZhao -> Xin Zhao

Now they work perfectly. I haven't tested them all, but I believe I won't have any problems.
