### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by anongoneviral** [ZeroLP/ExSharp-Base#8]
When I run the program everything works and then when I open League of Legends (the game not client) I keep getting this error:

"HRESULT: [0x88760868], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_DEVICELOST/DeviceLost], Message: Unknown"

I press continue and the ExSharp-Base just crashes

Help would be appreciated

**Comment by darkdawn29** [comment]
Trying running as admin after you've spawned in the rift

**Comment by anongoneviral** [comment]
Yes I run it as admin and after I spawn

**Comment by anongoneviral** [comment]
I think it has something to do with my Direct X version but I re-installed it and same error

**Comment by anongoneviral** [comment]
Nvm I got it to work, apparently it just doesnt work in full screen mode, borderless works fine
